### ISSUE TITLE
Support all #pragmas used by Liebherr

### ISSUE THREAD

**Issue by jordr** [statinf-software/llvm-project#2]
Liebherr has promised they would come back by a list of `#pragma` they may use by Thursday. Opening an issue to keep tabs on this.

**Comment by brouxel** [comment]
Did we get the full list in the end?

**Comment by jordr** [comment]
@slimbenamor ?

**Comment by SlimBenAmor** [comment]
I did not ask them ? but we can ask next time.

**Comment by jordr** [comment]
Ok, they said they would come up with one, but both myself/ourself and themselves failed to remember

**Comment by jordr** [comment]
Think this is somewhat solved by now
